server:
  port: 8099
spring:
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
      routes:
        - id: ms-product
          uri: http://localhost:8082
          predicates:
            - Path=/api-product/**
          filters:
            - PreFilter
            - PostFilter
        - id: ms-customer
          uri: http://localhost:8085
          predicates:
            - Path=/customer-natural/**, /customer-juridical/**
          filters:
            - PreFilter
            - PostFilter
        - id: ms-transaction
          uri: http://localhost:8084
          predicates:
            - Path=/api-transaction/**
          filters:
            - PreFilter
            - PostFilter
        - id: ms-customerproduct
          uri: http://localhost:8083
          predicates:
            - Path=/api-account-active/**, /api-account-pasive/**
          filters:
            - PreFilter
            - PostFilter
  application:
    name: ms-apigateway
